config/routes.rb
BrashCalibration::Application.routes.draw do

  resources :test_weights

  resources :certificates

  devise_for :users
  
  devise_scope :user do
    post 'update' => 'registrations/update'
    get 'login' => 'devise/sessions#new', :as => :login
    post 'login' => 'devise/sessions#create', :as => :user_session
    get 'logout' => 'devise/sessions#destroy', :as => :logout
    get 'signup' => 'devise/registrations#new', :as => :signup
    get 'account' => 'devise/registrations#edit', :as => :edit_account
  end

  root :to => 'customers#index'
  resources :customers 

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :customers
      resources :machines
    end
  end
  resources :machines do
    collection do
      delete 'destroy_multiple'
    end
  end

end

app/models/test_weight.rb
class TestWeight < ActiveRecord::Base
  attr_accessible :certificate_number, :date_calibrated, :name
end

app/controllers/test_weights_controller.rb
class TestWeightsController < ApplicationController
  # GET /test_weights
  # GET /test_weights.json
  def index
    
    @search = TestWeight.search(params[:q])
    @test_weights = @search.result
    @test_weights = TestWeight.where("date_calibrated > ?", Date.today() -  12.months).paginate( :per_page => 1, :page => params[:page])
   

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  # GET /test_weights/1
  # GET /test_weights/1.json
  def show
    @test_weight = TestWeight.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  # GET /test_weights/new
  # GET /test_weights/new.json
  def new
    @test_weight = TestWeight.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @test_weight }
    end
  end

  # GET /test_weights/1/edit
  def edit
    @test_weight = TestWeight.find(params[:id])
  end

  # POST /test_weights
  # POST /test_weights.json
  def create
    @test_weight = TestWeight.new(params[:test_weight])

    respond_to do |format|
      if @test_weight.save
        format.html { redirect_to @test_weight, notice: 'Test weight was successfully created.' }
        format.json { render json: @test_weight, status: :created, location: @test_weight }
      else
        format.html { render action: "new" }
        format.json { render json: @test_weight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /test_weights/1
  # PUT /test_weights/1.json
  def update
    @test_weight = TestWeight.find(params[:id])

    respond_to do |format|
      if @test_weight.update_attributes(params[:test_weight])
        format.html { redirect_to @test_weight, notice: 'Test weight was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @test_weight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_weights/1
  # DELETE /test_weights/1.json
  def destroy
    @test_weight = TestWeight.find(params[:id])
    @test_weight.destroy

    respond_to do |format|
      format.html { redirect_to test_weights_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/test_weights_helper.rb
module TestWeightsHelper
end

app/views/test_weights/_form.html.erb
<%= form_for(@test_weight, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @test_weight.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@test_weight.errors.count, "error") %> prohibited this test_weight from being saved:</h4>

      <ul>
      <% @test_weight.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Set_Name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :certificate_number, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :certificate_number, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date_calibrated, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :date_calibrated, :class => "form-control" %>
    </div>
  </div>
  
  
  <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %> 
      <%= link_to t('.back', :default => t("helpers.links.back")),
              :back, :class => 'btn btn-primary'  %>
      </div>        
  </div>
<% end %>

app/views/test_weights/edit.html.erb
<div class="page-header">
 <!-- <%= link_to test_weights_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>  --!>
  
    
  <h1>Editing test_weight</h1>
</div>

<%= render 'form' %>

app/views/test_weights/index.html.erb
<%- model_class = TestWeight -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="row">
  <div class="col-lg-3 pull-right">
      <div class="input-group custom-search-form">
           <%= search_form_for @search do |f| %>
              <div class="field">
                <%= f.label :date_calibrated_cont, "Search Test Weight" %>
                <%= f.text_field :date_calibrated_cont %>
              </div>
              <div class="actions"><%= f.submit "Search", :class => "button" %></div>
            <% end %>            
       </div><!-- /input-group -->
    </div>
</div>           
  

<table class="table ">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:Set_Name) %></th>
      <th><%= model_class.human_attribute_name(:Certificate_Number) %></th>
      <th><%= model_class.human_attribute_name(:Date_Calibrated) %></th>
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @test_weights.each do |test_weight| %>
      <tr class="selected-row">  
        <td data-open='<%= test_weight_path(test_weight) %>'><%= test_weight.name %></td>
        <td data-open='<%= test_weight_path(test_weight) %>'><%= test_weight.certificate_number %></td>
        <td data-open='<%= test_weight_path(test_weight) %>'><%= test_weight.date_calibrated %></td>
      
           
        <td>
          <%= link_to 'edit',edit_test_weight_path(test_weight), :class => "btn btn-primary" %>
          
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      test_weight,
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


            <% link_to "Add", "#new_test_weight_modal", :data => { :toggle=>"modal" }, :class => "btn btn-primary" %>
            
            <%= link_to "Add Test Weight", new_test_weight_path, :class => "btn btn-primary" %>
            
            
            
            <div class="modal fade" id="weight-modal-window">
              <div class="modal-dialog modal-lg">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                    <h4>Test_Weight</h4>
                  </div>
                  <div class="modal-body" id="edit_modal_body">
                    
                  </div>
                  <div class="modal-footer">
                    <hr/>
                  </div>
                </div>
              </div>
            </div>

  <div align="center"><%= will_paginate @test_weights, renderer: BootstrapPagination::Rails %>
         </div>
      

app/views/test_weights/new.html.erb
<div class="page-header">
  
  <h1>New test_weight</h1>
</div>

<%= render 'form' %>

app/views/test_weights/new.js.erb
$('#edit_modal_body').html("<%= escape_javascript(render :partial => "form", :test_weight => @test_weight) %>");
$('#weight-modal-window').modal('show');

app/views/test_weights/show.html.erb
<%- model_class = TestWeight -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Set_Name) %>:</strong></dt>
  <dd><%= @test_weight.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Certificate_number) %>:</strong></dt>
  <dd><%= @test_weight.certificate_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Date_Calibrated) %>:</strong></dt>
  <dd><%= @test_weight.date_calibrated %></dd>
  
</dl>

  <div class="form-actions">
              <%= link_to t('.back', :default => t("helpers.links.back")),
              test_weights_path, :class => 'btn btn-primary'  %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_test_weight_path(@test_weight), :class => 'btn btn-primary' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              test_weight_path(@test_weight),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  </div>