config/routes.rb
BrashCalibration::Application.routes.draw do

  resources :test_weights

  resources :certificates

  devise_for :users
  
  devise_scope :user do
    post 'update' => 'registrations/update'
    get 'login' => 'devise/sessions#new', :as => :login
    post 'login' => 'devise/sessions#create', :as => :user_session
    get 'logout' => 'devise/sessions#destroy', :as => :logout
    get 'signup' => 'devise/registrations#new', :as => :signup
    get 'account' => 'devise/registrations#edit', :as => :edit_account
  end

  root :to => 'customers#index'
  resources :customers 

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :customers
      resources :machines
    end
  end
  resources :machines do
    collection do
      delete 'destroy_multiple'
    end
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base

	has_many :machines, :dependent => :delete_all
	has_many :certificates, :dependent => :delete_all

 attr_accessible :account_number, :address, :name, :street, :town, :city, :telephone_number, :email_address, :contact_name

 validates :name, presence: true
 validates :account_number, presence: true

 default_scope :order => 'name ASC'

end

app/controllers/API/V1/customers_controller.rb
module Api
	module V1
		class CustomersController < ApplicationController 

			respond_to :json
			skip_before_filter :authenticate_user!

			def index
				respond_with Customer.all
			end

			def show
				respond_with Customer.find(params[:id])
			end

			def create
				respond_with Customer.create(params[:customer])
			end

			def update
				respond_with Customer.update(params[:id], params[:customer])
			end

			def destroy
				respond_with Customer.destroy(params[:id])
			end
		end
	end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @search = Customer.search(params[:q])
    @customers = @search.result.paginate( :per_page => 1, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])
    @machine = Machine.new
    @machines = @customer.machines
    @certificate = Certificate.new
    @certificates = @customer.certificates

    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end


  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
         
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
    end
  end

  
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer,  :html => { :class => 'form-horizontal' } do |f| %>
<div class="row">
  <div class="col-md-6">

    <div class="form-group">
      <%= f.label :account_number, "Acc No", :class => 'col-md-4 control-label' %>
      <div class="col-md-6">
  
        <%= f.text_field :account_number, :class => 'form-control', :placeholder => 'ACC No', :required => true %>
     
      </div>
    </div>
    <div class="form-group">
      <%= f.label :name, "Company Name", :class => 'col-md-4 control-label' %>
      <div class="col-md-8">
        <%= f.text_field :name, :class => 'form-control', :placeholder => 'Company Name' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :address, :class => 'col-md-4 control-label' %>
      <div class="col-md-8">
        <%= f.text_field :address, :class => 'form-control', :placeholder => 'Address' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :street, "", :class => 'col-md-4 control-label' %>
      <div class="col-md-8">
        <%= f.text_field :street, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :town, '', :class => 'col-md-4 control-label' %>
      <div class="col-md-8">
        <%= f.text_field :town, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :city, :class => 'col-md-4 control-label' %>
      <div class="col-md-8">
        <%= f.text_field :city, :class => 'form-control' %>
      </div>
    </div>
  </div> <!-- end left col -->
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :contact_name, 'Contact Name', :class => 'col-md-4 control-label' %>
      <div class="col-md-8">
        <%= f.text_field :contact_name, :class => 'form-control', :placeholder => 'Contact Name' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :telephone_number, 'Phone', :class => 'col-md-4 control-label' %>
      <div class="col-md-8">
        <%= f.text_field :telephone_number, :class => 'form-control', :placeholder => 'Telephone Number' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :email_address, 'Email', :class => 'col-md-4 control-label' %>
      <div class="col-md-8">
        <%= f.email_field :email_address, :class => 'form-control' %>
      </div>
    </div>
    <hr/>
    <div class="form-actions">
      <div class="col-md-8 pull-right">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    customers_path, :class => 'btn btn-primary' %>
      </div>
    </div>
    </hr>
  </div> <!-- End right col -->
</div><!-- close row -->

  
<% end %>

app/views/customers/edit.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1>Edit Customer</h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/edit.js.erb
$('#edit_modal_body').html("<%= escape_javascript(render :partial => "form", :customer => @customer) %>");
$('#modal-window').modal('show'); 

app/views/customers/index.html.erb
<%- model_class = Customer -%>
<div class="page-header">
<h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>



<div class="row">
    <div class="col-lg-3 pull-right">
            <div class="input-group custom-search-form">
            
                
<%= search_form_for @search do |f| %>
  <div class="field">
    <%= f.label :name_cont, "Search Customer" %>
    <%= f.text_field :name_cont, :placeholder => 'Company Name' %>
  </div>
    <div class="actions"><%= f.submit "Search", :class => "button" %></div>
<% end %>
   
              
              
             </button>
             </span>
             </div><!-- /input-group -->
        </div>
  </div>
<table class="table ">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:account_number) %></th>
      <th><%= model_class.human_attribute_name(:company_name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th>Post Code</th>
      <th>Contact Name</th>
      <th>Telephone</th>
      <th>Email</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr class="selected-row">
        <td data-open='<%= customer_path(customer) %>'><%= customer.account_number %></td>
        <td data-open='<%= customer_path(customer) %>'><%= customer.name %></td>
        <td data-open='<%= customer_path(customer) %>'><%= customer.address %></td>
        <td data-open='<%= customer_path(customer) %>'></td>
        <td data-open='<%= customer_path(customer) %>'> <%= customer.contact_name %> </td>
        <td data-open='<%= customer_path(customer) %>'> <%= customer.telephone_number %> </td>
        <td data-open='<%= customer_path(customer) %>'> <%= customer.email_address %> </td>
        <td>
          <%= link_to 'edit', edit_customer_path(customer, format: :js), :remote => true, :class => "btn btn-primary" %>
          
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_path(customer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>



            <%#= link_to "Add", "#new_customer_modal", :data => { :toggle=>"modal" }, :class => "btn btn-primary" %>
            <%= link_to "Add Customer", new_customer_path(format: :js), :remote => true, :class => "btn btn-primary" %>


            <div class="modal fade" id="modal-window">
              <div class="modal-dialog modal-lg">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                    <h4>Customer </h4>
                  </div>
                  <div class="modal-body" id="edit_modal_body">
                    
                  </div>
                  <div class="modal-footer">
                    <hr/>
                  </div>
                </div>
              </div>
            </div>
            
            
 
     
         <div align="center"><%= will_paginate @customers, renderer: BootstrapPagination::Rails %>
         </div>
      
  
            

app/views/customers/new.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/new.js.erb
$('#edit_modal_body').html("<%= escape_javascript(render :partial => "form", :customer => @customer) %>");
$('#modal-window').modal('show');

app/views/customers/show.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h2><%= @customer.name if @customer%></h2>
</div>
<div class="row">
  <div class="col-md-2">
    <strong><%= model_class.human_attribute_name(:account_number) %>:</strong><br/>
    <strong><%= model_class.human_attribute_name(:name) %>:</strong></br>
    <strong><%= model_class.human_attribute_name(:address) %>:</strong></br>
  </div>
  <div class="col-md-4">
    <%= @customer.account_number %><br/>
    <%= @customer.name %><br/>
    <%= @customer.address %><br/>
  </div>
</div>
<div class="row">
  <hr/>
</div>

<ul class="nav nav-tabs" role="tablist">
  <li class="active"><a href="#machines" role="tab" data-toggle="tab">Machine List</a></li>
  <li><a href="#certificates" role="tab" data-toggle="tab">Certificates</a></li>
</ul> 

<div class="tab-content">
  <div class="tab-pane active" id="machines">
    <%= form_tag destroy_multiple_machines_path, method: :delete, :remote => true do %>
      <div class="" id="machine_lines">
        <%= render "machines/machines" %>
      </div>
      <div class="row">
        <div class="col-md-3 pull-right">
          <%= submit_tag "Remove", :class => "btn btn-danger pull-right" %>
      &nbsp;
      
          <%= link_to "Add", "#new_machine_modal", :data => { :toggle=>"modal" }, :class => "btn btn-primary pull-right" %>
        </div>
      </div> <% end %>
  </div>




<div class="tab-pane" id="certificates">
  
  <%= render "certificates/certificates" %>

</div>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
  customers_path, :class => 'btn btn-success'  %>
</div>





<div class="modal" id="new_machine_modal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
        <h4> Add Machine </h4>
      </div>
      <div class="modal-body">
        <%= render 'machines/js_form' %>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="modal-window">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
        <h4><%=t '.title', :default => ['Machine Details'], :model => model_class.model_name.human.titleize %></h4>
      </div>
      <div class="modal-body" id="edit_modal_body">

      </div>
     
    </div>
  </div>
</div>
<div class="modal fade" id="certificate-modal-window">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
        <h4>New Certificate</h4>
      </div>
      <div class="modal-body" id="certificate_modal_body">
      </div>
    </div>
  </div>
</div>

app/views/customers/show.js.erb
$("#machine_lines").html("<%= escape_javascript( render(:partial => "machines/machines") ) %>");
$("#new_machine_modal").modal('hide');