config/routes.rb
BrashCalibration::Application.routes.draw do

  resources :test_weights

  resources :certificates

  devise_for :users
  
  devise_scope :user do
    post 'update' => 'registrations/update'
    get 'login' => 'devise/sessions#new', :as => :login
    post 'login' => 'devise/sessions#create', :as => :user_session
    get 'logout' => 'devise/sessions#destroy', :as => :logout
    get 'signup' => 'devise/registrations#new', :as => :signup
    get 'account' => 'devise/registrations#edit', :as => :edit_account
  end

  root :to => 'customers#index'
  resources :customers 

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :customers
      resources :machines
    end
  end
  resources :machines do
    collection do
      delete 'destroy_multiple'
    end
  end

end

app/models/certificate.rb
class Certificate < ActiveRecord::Base

	belongs_to :machine
	belongs_to :customer


  attr_accessible :certificate_number, :customer_id, :machine_id, :testpoint_1, :testpoint_2, :testpoint_3,
  :testpoint_4, :testpoint_5, :testpoint_6, :definitive_testpoint_1, :definitive_testpoint_2, :definitive_testpoint_3,
  :definitive_testpoint_4, :definitive_testpoint_5, :definitive_testpoint_6, :definitive_testpoint_1_dev,
  :definitive_testpoint_2_dev, :definitive_testpoint_3_dev, :definitive_testpoint_4_dev, :definitive_testpoint_5_dev,
  :definitive_testpoint_6_dev, :definitive_repeatability_1_load, :definitive_repeatability_2_load,
  :definitive_repeatability_3_load, :definitive_repeatability_1_result_1, :definitive_repeatability_2_result_1,
  :definitive_repeatability_3_result_1, :definitive_repeatability_1_result_2, :definitive_repeatability_2_result_2,
  :definitive_repeatability_3_result_2, :definitive_repeatability_1_result_3, :definitive_repeatability_2_result_3,
  :definitive_repeatability_3_result_3, :repeatability_1_unloaded, :repeatability_2_unloaded, :repeatability_3_unloaded,
  :repeatability_4_unloaded, :repeatability_5_unloaded, :repeatability_6_unloaded, :repeatability_1_loaded,
  :repeatability_2_loaded, :repeatability_3_loaded, :repeatability_4_loaded, :repeatability_5_loaded,
  :repeatability_6_loaded, :definitive_eccentric_1, :definitive_eccentric_2, :definitive_eccentric_3,
  :definitive_eccentric_4, :definitive_eccentric_5, :definitive_eccentric_6, :test_weight_1_set_number, :test_weight_1_date,
  :test_weight_2_set_number, :test_weight_2_date, :test_weight_3_set_number, :test_weight_3_date, :weight_id_1,
  :weight_id_2, :weight_id_3,
  :test_weight_1_certificate_number , :test_weight_2_certificate_number , :test_weight_3_certificate_number

  validates :machine_id, presence: true

  #after_initialize :set_suggested_test_points

  before_save :set_defaults, :calculate_tolerance_ranges, :get_certificate_number, :set_weights
  after_save :update_next_due

  def get_certificate_number
    begin
      last_no = Certificate.last.certificate_number  
      new_cert_number = last_no + 1 
      self.certificate_number = new_cert_number
    rescue 
      self.certificate_number = 1
    end
  end

  def set_defaults
  	
  	self.date_completed = Date.today
  	self.next_certification_date = next_due_date
  end

  def next_due_date
  	#TODO Create a function to update the next due date based on the machine schedule!!
  	#TODO Also update the schedule on machine with the new next due date 
  	self.machine.due_date + 12.months

  end
  # Virtual Attributes
  def weight_id_1

  end
  def weight_id_1=(val)
    @weight_id_1 = val
  end
  def weight_id_2

  end
  def weight_id_2=(val)
    @weight_id_2 = val
  end
  def weight_id_3

  end
  def weight_id_3=(val)
    @weight_id_3 = val
  end
 # Set the test weight details in teh certiifcate incase old certificates are deleted 
  def set_weights
    if @weight_id_1
      weight = TestWeight.find_by_id(@weight_id_1)
      self.test_weight_1_set_number = weight.name
      self.test_weight_1 = weight.date_calibrated
      self.test_weight_1_certificate_number = weight.certificate_number
    end
    if @weight_id_2
      weight = TestWeight.find_by_id(@weight_id_2)
      self.test_weight_2_set_number = weight.name
      self.test_weight_2 = weight.date_calibrated
      self.test_weight_2_certificate_number = weight.certificate_number
    end
    if @weight_id_3
      weight = TestWeight.find_by_id(@weight_id_3)
      self.test_weight_3_set_number = weight.name
      self.test_weight_3 = weight.date_calibrated
      self.test_weight_3_certificate_number = weight.certificate_number
    end
  end

  def calculate_tolerance_ranges
    machine = Machine.find_by_id(self.machine_id)
    u = "#{machine.units}"
    self.tolerance_1_range = "#{machine.division_size - machine.division_size } #{u} - #{machine.division_size * 500} #{u}"
    self.tolerance_2_range = "#{machine.division_size * 500} #{u} - #{machine.division_size * 2000} #{u}"
    self.tolerance_3_range = "#{machine.division_size * 2000} #{u} - #{machine.capacity} #{u}"
    self.tolerance_1_actual = "#{machine.division_size} #{u}"
    self.tolerance_2_actual = "#{machine.division_size * 2} #{u}"
    self.tolerance_3_actual = "#{machine.division_size * 3} #{u}"
    #TODO add schedule number of months to machine model
    self.next_certification_date = Date.today + 12.months
  end

  def update_next_due

    machine = Machine.find_by_id(self.machine_id)
    #TODO add schedule number of months to machine model
    new_date = Date.today + 12.months

    machine.update_attributes(:due_date => new_date, :last_calibration_date => Date.today )
    
  end


end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController


  def index
    @certificates = Certificate.all.paginate( :per_page => 1, :page => params[:page])


    respond_to do |format|
      format.html # index.html.erb
    end
  end


  def show
    @certificate = Certificate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @certificate = Certificate.new
    @machine = Machine.find(params[:machine])

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  def edit
    @certificate = Certificate.find(params[:id])
  end


  def create
    @certificate = Certificate.new(params[:certificate])

    respond_to do |format|
      if @certificate.save
        format.html { redirect_to :back, notice: 'Certificate was successfully created.' }
      else
        format.html { redirect_to :back, error: 'Error Creating Certificate.'  }
      end
    end
  end

  def update
    @certificate = Certificate.find(params[:id])

    respond_to do |format|
      if @certificate.update_attributes(params[:certificate])
        format.html { redirect_to @certificate, notice: 'Certificate was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end


  def destroy
    @certificate = Certificate.find(params[:id])
    @certificate.destroy

    respond_to do |format|
      format.html { redirect_to :back }
    end
  end
end

app/helpers/certificates_helper.rb
module CertificatesHelper

	def tp(capacity,multiplier)
		if capacity
			capacity / 5 * multiplier
		else
			0
		end
	end

end

app/views/certificates/_certificates.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
            <th></th>
            <th>No</th>
            <th>Machine</th> 
            <th>Serial No</th>
            <th>Date Calibrated</th>
            <th>Next Due</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @certificates) do |certificate|  %>
            <td><%= check_box_tag "certificates[]", certificate.id %></td>
            <td><%= certificate.certificate_number %></td>
            <td><%= certificate.machine.make if certificate.machine %></td>
            <td><%= certificate.machine.serial_number if certificate.machine %></td>
            <td><%= certificate.date_completed %></td>
            <td><%= certificate.next_certification_date %></td>
            <td>

              <%= link_to 'View', certificate, :"data-popup" => true, :class => 'btn btn-primary'  %>
        <% link_to 'Edit', edit_certificate_path(certificate) %>
        <%= link_to 'Destroy', certificate, :class => 'btn  btn-danger', method: :delete, data: { confirm: 'Are you sure?' }  %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/certificates/_form.html.erb
<%= form_for(@certificate, :html => { :class => "form-horizontal" }) do |f| %>
<% if @certificate.errors.any? %>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <h4><%= pluralize(@certificate.errors.count, "error") %> prohibited this certificate from being saved:</h4>

  <ul>
    <% @certificate.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<!-- Tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><a href="#Linearity" role="tab" data-toggle="tab">Test Results</a></li>
  <li><a href="#settings" role="tab" data-toggle="tab">Settings</a></li>
</ul>

<%= f.hidden_field :customer_id,:class => "form-control", :value => @machine.customer_id if @machine  %>
<%= f.hidden_field :machine_id,:class => "form-control", :value => @machine.id if @machine  %>

<div class="tab-content">
  <div class="tab-pane active" id="Linearity">

    <div class="row">
      <div class="col-md-12">
        <hr/>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
        <h5 class="light-font">Test Weight Details</h5>
      </div>
      <div class="col-md-3">
        <%= f.collection_select :weight_id_1, TestWeight.order('name ASC').all, :id, :name, {:include_blank => ' Select Test Weight'} %>
      </div>
      <div class="col-md-3">
        <%= f.collection_select :weight_id_2, TestWeight.order('name ASC').all, :id, :name, {:include_blank => ' Select Test Weight'}%>
      </div>
      <div class="col-md-3">
        <%= f.collection_select :weight_id_3, TestWeight.order('name ASC').all, :id, :name, {:include_blank => ' Select Test Weight'} %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <hr/>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-2">
        </div>
        <div class="col-md-5">
          <h5 class="light-font text-center"> Post Adjustment Linearity</h5>
        </div>
        <div class="col-md-5">
          <h5 class="light-font text-center">Post Adjustment Repeatability </h5>
        </div>
      </div>
    </div> <!-- end row -->
    <div class="row" id="cal-content">
      <div class="col-md-2 border-top border-right">
        <div class="col-md-10">
          <h6><small>Test Points</small></h6>
          <div class="form-group">
            <%= f.text_field :testpoint_1, :class => 'form-control', :value => 0 %>
          </div>
          <div class="form-group">
            <%= f.text_field :testpoint_2, :class => 'form-control', :value => tp(@machine.capacity, 1) if @machine %>
          </div>
          <div class="form-group">
            <%= f.text_field :testpoint_3, :class => 'form-control', :value => tp(@machine.capacity, 2) if @machine %>
          </div>
          <div class="form-group">
            <%= f.text_field :testpoint_4, :class => 'form-control', :value => tp(@machine.capacity, 3) if @machine %>
          </div>
          <div class="form-group">
            <%= f.text_field :testpoint_5, :class => 'form-control', :value => tp(@machine.capacity, 4) if @machine %>
          </div>
          <div class="form-group">
            <%= f.text_field :testpoint_6, :class => 'form-control', :value => tp(@machine.capacity, 5) if @machine %>
          </div>
        </div>
      </div>
      <div class="col-md-10 border-top ">

        <div class="col-md-6 ">
          <div class="col-md-5">
            <h6><small>Loading</small></h6>
            <div class="form-group">
              <%= f.text_field :definitive_testpoint_1, :class => 'form-control'%>
            </div>
            <div class="form-group">
              <%= f.text_field :definitive_testpoint_2, :class => 'form-control'%>
            </div>
            <div class="form-group">
              <%= f.text_field :definitive_testpoint_3, :class => 'form-control'%>
            </div>
            <div class="form-group">
              <%= f.text_field :definitive_testpoint_4, :class => 'form-control'%>
            </div>
            <div class="form-group">
              <%= f.text_field :definitive_testpoint_5, :class => 'form-control'%>
            </div>
            <div class="form-group">
              <%= f.text_field :definitive_testpoint_6, :class => 'form-control'%>
            </div>
          </div>
          <div class="col-md-1">
          </div>
          <div class="col-md-3">
            <h6><small>Dev</small></h6>
            <div class="form-group">
              <%= f.text_field :definitive_testpoint_1_dev, :class => 'form-control', :readonly => true%>
            </div>
            <div class="form-group">
              <%= f.text_field :definitive_testpoint_2_dev, :class => 'form-control', :readonly => true%>
            </div>
            <div class="form-group">
              <%= f.text_field :definitive_testpoint_3_dev, :class => 'form-control', :readonly => true%>
            </div>
            <div class="form-group">
              <%= f.text_field :definitive_testpoint_4_dev, :class => 'form-control', :readonly => true%>
            </div>
            <div class="form-group">
              <%= f.text_field :definitive_testpoint_5_dev, :class => 'form-control', :readonly => true%>
            </div>
            <div class="form-group">
              <%= f.text_field :definitive_testpoint_6_dev, :class => 'form-control', :readonly => true%>
            </div>
          </div>
          <div class="col-md-1 border-right">

          </div>
        </div>
        <!-- end left col -->
        <div class="col-md-6 border-right">
          <div class="col-md-6">
            <h6><small>UnLoaded</small></h6>
            <div class="form-group">
              <%= f.text_field :repeatability_1_unloaded, :class => 'form-control', :value => 0%>
            </div>
            <div class="form-group">
              <%= f.text_field :repeatability_2_unloaded, :class => 'form-control', :value => 0 %>
            </div>
            <div class="form-group">
              <%= f.text_field :repeatability_3_unloaded, :class => 'form-control', :value => 0 %>
            </div>
            <div class="form-group">
              <%= f.text_field :repeatability_4_unloaded, :class => 'form-control', :value => 0 %>
            </div>
            <div class="form-group">
              <%= f.text_field :repeatability_5_unloaded, :class => 'form-control', :value => 0 %>
            </div>
            <div class="form-group">
              <%= f.text_field :repeatability_6_unloaded, :class => 'form-control', :value => 0 %>
            </div>
          </div>
          <div class="col-md-5 pull-right">
            <h6><small>Loaded</small></h6>
            <div class="form-group">
              <%= f.text_field :repeatability_1_loaded, :class => 'form-control'%>
            </div>
            <div class="form-group">
              <%= f.text_field :repeatability_2_loaded, :class => 'form-control'%>
            </div>
            <div class="form-group">
              <%= f.text_field :repeatability_3_loaded, :class => 'form-control'%>
            </div>
            <div class="form-group">
              <%= f.text_field :repeatability_4_loaded, :class => 'form-control'%>
            </div>
            <div class="form-group">
              <%= f.text_field :repeatability_5_loaded, :class => 'form-control'%>
            </div>
            <div class="form-group">
              <%= f.text_field :repeatability_6_loaded, :class => 'form-control'%>
            </div>
          </div> 
        </div> 
      </div>
    </div> <!-- end content row -->
    <div class="row border-top"> <!-- Corner Tests -->
      <div class="col-md-6 border-right"> <!-- left col -->
        <div class="col-md-12 ">
          <h5 class="light-font text-center "> Escentric Loading</h5>
          <div class="col-md-2">
            <%= f.label :definitive_eccentric_1,"1", :class=>"form-label" %>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <%= f.text_field :definitive_eccentric_1, :class => 'form-control' %>
            </div>
          </div>
          <div class="col-md-2 ">
            <%= f.label :definitive_eccentric_2,"2", :class=>"form-label" %>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <%= f.text_field :definitive_eccentric_2, :class => 'form-control' %>
            </div>
          </div>
          <div class="col-md-2 ">
            <%= f.label :definitive_eccentric_3,"3", :class=>"form-label" %>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <%= f.text_field :definitive_eccentric_3, :class => 'form-control' %>
            </div>
          </div>
          <div class="col-md-2 ">
            <%= f.label :definitive_eccentric_4,"4", :class=>"form-label" %>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <%= f.text_field :definitive_eccentric_4, :class => 'form-control' %>
            </div>
          </div>
          <div class="col-md-2 ">
            <%= f.label :definitive_eccentric_5,"5", :class=>"form-label" %>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <%= f.text_field :definitive_eccentric_5, :class => 'form-control' %>
            </div>
          </div>
          <div class="col-md-2 ">
            <%= f.label :definitive_eccentric_6,"6", :class=>"form-label" %>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <%= f.text_field :definitive_eccentric_6, :class => 'form-control' %>
            </div>
          </div>


        </div>
      </div>
      <div class="col-md-6">
        <div class="col-md-12">
          <%= image_tag("corner.jpg", :class=> "corner_image") %>
        </div>   
      </div>
    </div>
  </div><!-- End of page 1 -->
</div> <!-- Close Linearity Tab -->
 
  <!-- Close repeatability Tab -->
</div> <!-- Close Tabs-->


<div class="modal-footer">
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>

app/views/certificates/edit.html.erb
<div class="page-header">
  <%= link_to certificates_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @certificate, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing certificate</h1>
</div>

<%= render 'form' %>

app/views/certificates/index.html.erb
<div class="page-header">
  <%= link_to new_certificate_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Certificate
  <% end %>
  <h1>Listing certificates</h1>
</div>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
            <th>Certificate number</th>
            <th>Machine</th>
            <th>Customer</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @certificates) do |certificate| %>
            <td><%= certificate.certificate_number %></td>
            <td><%= certificate.machine_id %></td>
            <td><%= certificate.customer_id %></td>
            <td><%= link_to 'Show', certificate, :class => "btn btn-primary"  %>
        <%= link_to 'Edit', edit_certificate_path(certificate),:class => "btn btn-primary"  %>
        <%= link_to 'Destroy', certificate, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger"  %></td>
      <% end %>
    </tbody>
  </table>
</div>


<div align="center"><%= will_paginate @certificates, renderer: BootstrapPagination::Rails %>
         </div>

app/views/certificates/new.html.erb
<div class="page-header">
  <%= link_to certificates_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New certificate</h1>
</div>

<%= render 'form' %>

app/views/certificates/new.js.erb
$('#certificate_modal_body').html("<%= escape_javascript(render :partial => "certificates/form", :certificate => @certificate) %>");
$('#certificate-modal-window').modal('show');