config/routes.rb
BrashCalibration::Application.routes.draw do

  resources :test_weights

  resources :certificates

  devise_for :users
  
  devise_scope :user do
    post 'update' => 'registrations/update'
    get 'login' => 'devise/sessions#new', :as => :login
    post 'login' => 'devise/sessions#create', :as => :user_session
    get 'logout' => 'devise/sessions#destroy', :as => :logout
    get 'signup' => 'devise/registrations#new', :as => :signup
    get 'account' => 'devise/registrations#edit', :as => :edit_account
  end

  root :to => 'customers#index'
  resources :customers 

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :customers
      resources :machines
    end
  end
  resources :machines do
    collection do
      delete 'destroy_multiple'
    end
  end

end

app/models/machine.rb
class Machine < ActiveRecord::Base

	belongs_to :customer
	has_many :certificates, :foreign_key => 'machine_id'

  attr_accessible :capacity, :customer_id, :division_size, :due_date, :last_calibration_date, :make, :model, :serial_number, :units,
  					:capacity_2, :division_size_2, :capacity_3, :division_size_3, :multiRange 

  	validates :customer_id, presence: true
end

app/controllers/API/V1/machines_controller.rb
module Api
	module V1
		class MachinesController < ApplicationController 

			respond_to :json
			skip_before_filter :authenticate_user!

			def index
				respond_with Machine.all
			end

			def show
				respond_with Machine.find(params[:id])
			end

			def create
				respond_with Machine.create(params[:machine])
			end

			def update
				respond_with Machine.update(params[:id], params[:machine])
			end

			def destroy
				respond_with Machine.destroy(params[:id])
			end
			
			def destroy_multiple
    			respond_with Machine.destroy(params[:machines])
    		end
		end
	end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  # GET /machines
  # GET /machines.json
  def index
    @search = Machine.search(params[:q])
    @machines = @search.result.paginate( :per_page => 1, :page => params[:page])


    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /machines/1
  # GET /machines/1.json
  def show
    @machine = Machine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /machines/new
  # GET /machines/new.json
  def new
    @machine = Machine.new

    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @machine }
    end
  end

  # GET /machines/1/edit
  def edit
    @machine = Machine.find(params[:id])
  end

  def create
    @machine = Machine.new(params[:machine])

    respond_to do |format|
      if @machine.save
        format.html { redirect_to @machine.customer anchor: 'machines', notice: 'Machine was successfully created.' }
        #format.json { render json: @machine, status: :created, location: @machine }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /machines/1
  # PUT /machines/1.json
  def update
    @machine = Machine.find(params[:id])

    respond_to do |format|
      if @machine.update_attributes(params[:machine])
        format.html { redirect_to :back, notice: 'Machine was successfully updated.' }
      else
        format.html { render action: "edit" }

      end
    end
  end

  # DELETE /machines/1
  # DELETE /machines/1.json
  def destroy
    @machine = Machine.find(params[:id])
    @machine.destroy

    respond_to do |format|
      format.html { redirect_to machines_url }
    end
  end

  def destroy_multiple
    Machine.destroy(params[:machines])

    respond_to do |format|
      format.html { redirect_to :back }
    end
  end

end

app/helpers/machines_helper.rb
module MachinesHelper

	def pretty_number(number)
		number ||= 0
		if number >= 1.0 
			return number.round()
		else
			number
		end
	end

	def background(date)
		#TODO Add an Icon instead looks poo
		if date <= Date.today
			"color: red;"
		else
			"color: green;"
		end
	end

end

app/views/machines/_form.html.erb
<div class="row">
  <%= form_for @machine, :html => { :class => 'form-horizontal', :id => 'thisform' } do |f| %>
  <div class="col-md-6" id="left-col">
    <%= f.hidden_field :customer_id, :value => @customer.id if @customer %>
    <div class="form-group">
      <%= f.label :make, :class => 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <%= f.text_field :make, :class => 'form-control', :placeholder => 'Equipment Manufacturer' %>
        <p class="help-block">Manufacturer i.e Avery , Sartorius, Ohaus Brash</p>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :model, :class => 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <%= f.text_field :model, :class => 'form-control', :placeholder => 'Model Number' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :serial_number,"Serial No:",  :class => 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <%= f.text_field :serial_number, :class => 'form-control', :placeholder => 'Serial Number or ID Number' %>
      </div>
    </div>
  </div>
  <div class="col-md-6" id="right-col">
    <div class="form-group">
      <%= f.label :capacity, :class => 'col-sm-3 control-label' %>
      <div class="col-sm-8">
        <div class="col-md-7">
          <%= f.number_field :capacity, :class => 'form-control', :placeholder => 'Max'%>
        </div>
        <div class='col-md-5'>
          <%= f.text_field :division_size, :class => 'form-control', :placeholder => 'Div' %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class='col-md-4'>
        <%= f.label :multiRange, :class => 'col-sm-4 control-label' %>
      </div>
      <%= f.check_box :multiRange, :class => 'form-control col-sm-5' %> 
    </div>
    <div id='multiRange'>
      <div class="form-group">
        <%= f.label :capacity_2, :class => 'col-sm-3 control-label' %>
        <div class="col-sm-8">
          <div class="col-md-7">
            <%= f.number_field :capacity_2, :class => 'form-control', :placeholder => 'Max'%>
          </div>
          <div class='col-md-5'>
            <%= f.text_field :division_size_2, :class => 'form-control', :placeholder => 'Div' %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :capacity_3, :class => 'col-sm-3 control-label' %>
        <div class="col-sm-8">
          <div class="col-md-7">
            <%= f.number_field :capacity_3, :class => 'form-control', :placeholder => 'Max'%>
          </div>
          <div class='col-md-5'>
            <%= f.text_field :division_size_3, :class => 'form-control', :placeholder => 'Div' %>
          </div>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :units, :class => 'col-sm-3 control-label' %>
      <div class="col-sm-5">
        <%= f.select :units, options_for_select([['Kg'],['g']], @machine.units),{:include_blank => false}, {:class => 'form-control'} %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :last_calibration_date, 'Last Cal', :class => 'col-sm-3 control-label' %>
      <div class="col-sm-5">
        <%= f.text_field :last_calibration_date, :class => 'form-control', :id => 'date1',:placeholder => 'Last Cal Date' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :due_date, :class => 'col-sm-3 control-label' %>
      <div class="col-sm-5">
        <%= f.text_field :due_date, :class => 'form-control',:id => 'date2', :placeholder => 'Next Cal Date'  %>
      </div>
    </div>
  </div>
</div>
<div class="modal-footer">
  <%= f.submit nil, :class=>'btn btn-success', :onclick => 'document.forms["thisform"].submit()' %>
   <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    :back, :class => 'btn btn-primary' %>
</div>

<% end %> 
<script type="text/javascript">
  $('#date1, #date2').datepicker({dateFormat: "dd-mm-yy"});
</script>

app/views/machines/_js_form.html.erb
<div class="row">
<%= form_for @machine, :html => { :class => 'form-horizontal' } do |f| %>
	<div class="col-md-6" id="left-col">
		<%= f.hidden_field :customer_id, :value => @customer.id if @customer %>
		<div class="form-group">
			<%= f.label :make, :class => 'col-sm-3 control-label' %>
			<div class="col-sm-9">
				<%= f.text_field :make, :class => 'form-control', :placeholder => 'Equipment Manufacturer' %>
				<p class="help-block">Manufacturer i.e Avery , Sartorius, Ohaus Brash</p>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :model, :class => 'col-sm-3 control-label' %>
			<div class="col-sm-9">
				<%= f.text_field :model, :class => 'form-control', :placeholder => 'Model Number' %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :serial_number,"Serial No:",  :class => 'col-sm-3 control-label' %>
			<div class="col-sm-9">
				<%= f.text_field :serial_number, :class => 'form-control', :placeholder => 'Serial Number or ID Number' %>
			</div>
		</div>
	</div>
	<div class="col-md-6" id="right-col">
		<div class="form-group">
			<%= f.label :capacity, :class => 'col-sm-3 control-label' %>
			<div class="col-sm-8">
				<div class="col-md-7">
					<%= f.number_field :capacity, :class => 'form-control', :placeholder => 'Max'%>
				</div>
				<div class='col-md-5'>
					<%= f.text_field :division_size, :class => 'form-control', :placeholder => 'Div' %>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class='col-md-4'>
     			<%= f.label :multiRange, :class => 'col-sm-4 control-label' %>
     		</div>
     		<%= f.check_box :multiRange, :class => 'form-control col-sm-5' %> 
    	</div>
    	<div id='multiRange'>
	    	<div class="form-group">
				<%= f.label :capacity_2, :class => 'col-sm-3 control-label' %>
				<div class="col-sm-8">
					<div class="col-md-7">
						<%= f.number_field :capacity_2, :class => 'form-control', :placeholder => 'Max'%>
					</div>
					<div class='col-md-5'>
						<%= f.text_field :division_size_2, :class => 'form-control', :placeholder => 'Div' %>
					</div>
				</div>
			</div>
			<div class="form-group">
				<%= f.label :capacity_3, :class => 'col-sm-3 control-label' %>
				<div class="col-sm-8">
					<div class="col-md-7">
						<%= f.number_field :capacity_3, :class => 'form-control', :placeholder => 'Max'%>
					</div>
					<div class='col-md-5'>
						<%= f.text_field :division_size_3, :class => 'form-control', :placeholder => 'Div' %>
					</div>
				</div>
			</div>
		</div>

		<div class="form-group">
			<%= f.label :units, :class => 'col-sm-3 control-label' %>
			<div class="col-sm-5">
				<%= f.select :units, options_for_select([['Kg'],['g']], @machine.units),{:include_blank => false}, {:class => 'form-control'} %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :last_calibration_date, 'Last Cal', :class => 'col-sm-3 control-label' %>
			<div class="col-sm-5">
				<%= f.text_field :last_calibration_date, :class => 'form-control', :placeholder => 'Last Cal Date'%>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :due_date, :class => 'col-sm-3 control-label' %>
			<div class="col-sm-5">
				<%= f.text_field :due_date, :value => Date.today, :class => 'form-control', :placeholder => 'Next Cal Date'  %>
			</div>
		</div>
	</div>
</div>
</div>
      <div class="modal-footer">
      	<%= f.submit nil, :class=>'btn btn-success' %>
      </div>
	
<% end %>	

app/views/machines/_machines.html.erb
<%- model_class = Machine -%>

<table class="table">
  <thead>
    <tr>
      <th><%= check_box_tag "selectAll" %></th>
      <th><%= model_class.human_attribute_name(:make) %></th>
      <th><%= model_class.human_attribute_name(:model) %></th>
      <th><%= model_class.human_attribute_name(:serial_number) %></th>
      <th><%= model_class.human_attribute_name(:capacity) %></th>
      <th><%= model_class.human_attribute_name(:division_size) %></th>
      <th><%= model_class.human_attribute_name(:last_calibration_date) %></th>
      <th>Next Due Date</th>
    </tr>
  </thead>
  <tbody>
    <% if @machines and @machines.count >0 %>
      <% @customer.machines.each do |machine| %>
        <tr class="selected-row"  style=" <%= background(machine.due_date) %> " >
          <td><%= check_box_tag "machines[]", machine.id %></td>
          <td data-open='<%= certificate_path(machine.certificates.last) unless machine.certificates.blank? %>'><%= machine.make %></td>
          <td data-open='<%= certificate_path(machine.certificates.last) unless machine.certificates.blank? %>'><%= machine.model %></td>
          <td data-open='<%= certificate_path(machine.certificates.last) unless machine.certificates.blank? %>'><%= machine.serial_number %></td>
          <td data-open='<%= certificate_path(machine.certificates.last) unless machine.certificates.blank? %>'><%= machine.capacity %>&nbsp; <%= machine.units %></td>
          <td data-open='<%= certificate_path(machine.certificates.last) unless machine.certificates.blank? %>'><%= pretty_number(machine.division_size) %> &nbsp; <%= machine.units %></td>
          <td data-open='<%= certificate_path(machine.certificates.last) unless machine.certificates.blank? %>'><%= machine.last_calibration_date %></td>
          <td data-open='<%= certificate_path(machine.certificates.last) unless machine.certificates.blank? %>'><%= machine.due_date %></td>
          <td><%= link_to 'edit', edit_machine_path(machine, format: :js), :remote => true, :class => "btn btn-primary" %>
              <%= link_to 'New Certificate', new_certificate_path(:machine => machine.id, format: :js), :remote => true, :class => "btn btn-default btn btn-success" %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/machines/edit.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/machines/edit.js.erb
$('#edit_modal_body').html("<%= escape_javascript(render :partial => "machines/form", :machine => @machine) %>");
$('#modal-window').modal('show');

app/views/machines/index.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<div class="row">
  <div class="col-lg-3 pull-right">
      <div class="input-group custom-search-form">
           <%= search_form_for @search do |f| %>
              <div class="field">
                <%= f.label :make_cont, "Search Machine" %>
                <%= f.text_field :make_cont, :placeholder => ' Make Type' %>
              </div>
              <div class="actions"><%= f.submit "Search", :class => "button" %></div>
            <% end %>            
       </div><!-- /input-group -->
    </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:customer_id) %></th>
      <th><%= model_class.human_attribute_name(:make) %></th>
      <th><%= model_class.human_attribute_name(:model) %></th>
      <th><%= model_class.human_attribute_name(:serial_number) %></th>
      <th><%= model_class.human_attribute_name(:capacity) %></th>
      <th><%= model_class.human_attribute_name(:last_calibration_date) %></th>
      <th><%= model_class.human_attribute_name(:due_date ) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @machines.each do |machine| %>
      <tr>
        <td><%= link_to machine.id, machine_path(machine) %></td>
        <td><%= machine.customer.name if machine.customer%></td>
        <td><%= machine.make %></td>
        <td><%= machine.model %></td>
        <td><%= machine.serial_number %></td>
        <td><%= machine.capacity %>&nbsp; <%= machine.units %></td>
        <td><%= machine.last_calibration_date %></td>
        <td><%= machine.due_date %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_machine_path(machine), :class => 'btn btn-primary' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      machine_path(machine),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_machine_path,
            :class => 'btn btn-primary' %>
            
            
            <div align="center"><%= will_paginate @machines, renderer: BootstrapPagination::Rails %>
         </div>

app/views/machines/new.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/machines/new.js.erb
$('#edit_modal_body').html("<%= escape_javascript(render :partial => "machines/js_form", :machine => @machine) %>");
$('#modal-window').modal('show');

app/views/machines/show.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:customer_id) %>:</strong></dt>
  <dd><%= @machine.customer_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:make) %>:</strong></dt>
  <dd><%= @machine.make %></dd>
  <dt><strong><%= model_class.human_attribute_name(:model) %>:</strong></dt>
  <dd><%= @machine.model %></dd>
  <dt><strong><%= model_class.human_attribute_name(:serial_number) %>:</strong></dt>
  <dd><%= @machine.serial_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:capacity) %>:</strong></dt>
  <dd><%= @machine.capacity %></dd>
  <dt><strong><%= model_class.human_attribute_name(:division_size) %>:</strong></dt>
  <dd><%= @machine.division_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:units) %>:</strong></dt>
  <dd><%= @machine.units %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_calibration_date) %>:</strong></dt>
  <dd><%= @machine.last_calibration_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:due_date) %>:</strong></dt>
  <dd><%= @machine.due_date %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              machines_path, :class => 'btn btn-primary'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_machine_path(@machine), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              machine_path(@machine),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>